### ISSUE TITLE
Config File "caduceus" Not Found

### ISSUE THREAD

**Issue by davidrneves** [Comcast/caduceus#61]
When I tried to start the caduceus service I get the following error: 
"Unable to initialize Viper environment: Config File 'caduceus' Not Found in '[/etc/caduceus / /home/ddp/.caduceus /home/ddp/Projects/caduceus/src/caduceus]".

I assume a configuration file is necessary to start the service correctly but I didn't found any documentation of it. Could you please provide some examples of a configuration file?

**Comment by schmidtw** [comment]
Viper looks in the 3 locations you listed when invoked where you invoked it:
```
[/etc/caduceus / /home/ddp/.caduceus /home/ddp/Projects/caduceus/src/caduceus]
```

Typically, we have been using the RPM which installs a file here: `/etc/caduceus/caduceus.json` that contains the default configuration.  You can copy [that file](https://github.com/Comcast/caduceus/blob/master/etc/caduceus/caduceus.json) into one of the above mentioned locations when you invoke `caduceus` and the viper library will find it.

**Comment by schmidtw** [comment]
If still a problem please re-open.
